version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql://apex_user:${DB_PASSWORD}@db:3306/apex_digital
      - JWT_SECRET_KEY=${JWT_SECRET}
      - FLASK_SECRET_KEY=${FLASK_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PAYFAST_MERCHANT_ID=${PAYFAST_MERCHANT_ID}
      - PAYFAST_MERCHANT_KEY=${PAYFAST_MERCHANT_KEY}
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=apex_digital
      - MYSQL_USER=apex_user
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./database/schemas/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
      - ./deployment/ssl:/etc/nginx/ssl
    depends_on:
      - backend

volumes:
  db_data:
